import {
  project1Laptop,
  project1Mobile,
  project2Laptop,
  project2Mobile,
  project3Laptop,
  project3Mobile,
  project4Laptop,
  project4Mobile,
  project5Laptop,
  project5Mobile,
  project6Laptop,
  project6Mobile,
  tani,
  jc,
} from "./projectImages";

export const projectData = [
  {
    id: 1,
    image: tani,
    transitionImage: tani,
    title: "Tanishq Website Clone",
    codeLink: "https://github.com/Luke0912/Tanishq",
    liveLink: "https://tanishq-clone.netlify.app/",
  },
  {
    id: 2,
    image: project2Laptop,
    transitionImage: project2Mobile,
    title: "Resume Builder",
    codeLink: "https://github.com/sunnyshk/Resume-Builder-App",
    // liveLink: "https://lediable.netlify.app/",
  },
  {
    id: 3,
    image: jc,
    transitionImage: jc,
    title: "JCrew Website Clone",
    codeLink: "https://github.com/sunnyshk/JCrew-Project",
    liveLink: "https://jcrew-eight.vercel.app/",
  },
  // {
  //   id: 4,
  //   image: project4Laptop,
  //   transitionImage: project4Mobile,
  //   title: "IT Company",
  //   codeLink: "https://github.com/monciego/coderig-landing-page",
  //   liveLink: "https://codeegrid.netlify.app/",
  // },
  // {
  //   id: 5,
  //   image: project5Laptop,
  //   transitionImage: project5Mobile,
  //   title: "Gym Fitness Website",
  //   codeLink: "https://github.com/monciego/intrepide",
  //   liveLink: "https://intrepide.netlify.app/",
  // },
  // {
  //   id: 6,
  //   image: project6Laptop,
  //   transitionImage: project6Mobile,
  //   title: "Space Tourism",
  //   codeLink: "https://github.com/monciego/space-tourism",
  //   liveLink: "https://spacetourism-monciego.netlify.app/",
  // },
];
